### PR TITLE
Form validation

### PR DESCRIPTION
**Pull request by gsmalik030**
In this branch:

We added Email type Validation.
We added the pattern Email Validation to avoid uppercase letters in email.

### CODE REVIEW

**Review by levy002 — CHANGES_REQUESTED** [review]
## Hello @gsmalik030 & @Rachelwebdev   , :wave:
### I'm Levy, your PR reviewer

Excellent work :sunglasses: 
There are some issues that you still need to work on to go to the next project but you are almost there!



## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly make sure to set up the `ES-LINT` linter correctly so it runs to check if there are no errors in your JavaScript code. I recommend you take a step back and read this[ lesson](https://github.com/microverseinc/linters-config/blob/master/html-css-js) to understand it clearly and follow the guideline to set it correctly.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gsmalik030** [comment]
@levy002  I'm sorry but I couldn't understand it on my side it's not showing an error can you please help me to notify the exact problem? I will be really grateful .

Thank you 👍

**Comment by levy002** [comment]
Hello @gsmalik030, what I meant was that your PR is only checking the `html` with `lighthouse` and `webhint`, and is checking the `css` code with `stylint` linter but there is no `es-lint` linter for checking `javascript` code. I am requesting to add the `es-lint` linter.

   ### Checks on your PR
   image

   ### hOW CHECK MUST LOOK
   image

**Review by ichala — APPROVED** [review]
Hi @gsmalik030   ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
